<?php

declare(strict_types=1);

namespace Dawn\Tests\Browser\Acceptance;

use Dawn\Tests\Browser\BrowserTestCase;
use Laravel\Dusk\Browser;

/**
 * THE ACCEPTANCE TEST.
 *
 * Every test body below is written exactly as it would appear in an existing
 * Laravel Dusk suite - including the `use Laravel\Dusk\Browser;` import,
 * which Dawn's compatibility autoloader resolves because laravel/dusk is not
 * installed. Only the base class differs. If these pass, a real Dusk suite's
 * bodies run unchanged on Playwright.
 */
final class DuskCompatibilityTest extends BrowserTestCase
{
    /**
     * The test generated by `php artisan dusk:install` (ExampleTest.php),
     * body unchanged.
     */
    public function test_basic_example(): void
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/')
                ->assertSee('Welcome');
        });
    }

    /**
     * A registration-form test in the style of the Laravel Dusk
     * documentation examples, body unchanged.
     */
    public function test_user_can_fill_registration_form(): void
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/form.html')
                ->type('name', 'Taylor Otwell')
                ->type('email', 'taylor@laravel.com')
                ->select('role', 'admin')
                ->radio('plan', 'pro')
                ->check('terms')
                ->assertInputValue('name', 'Taylor Otwell')
                ->assertSelected('role', 'admin')
                ->assertRadioSelected('plan', 'pro')
                ->assertChecked('terms')
                ->press('Create Account')
                ->assertPathIs('/second.html')
                ->assertSee('The second page');
        });
    }

    /**
     * Async UI: Dusk-documented waiting patterns, body unchanged and with no
     * sleeps anywhere.
     */
    public function test_dashboard_loads_asynchronous_content(): void
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/wait.html')
                ->waitForText('Loaded via JavaScript!')
                ->waitFor('@late')
                ->whenAvailable('.late-arrival', function (Browser $panel) {
                    $panel->assertSee('Loaded via JavaScript!');
                })
                ->waitUntilMissing('#vanishing')
                ->waitUntil('window.dawnReady')
                ->waitForLink('Late link')
                ->clickLink('Late link')
                ->waitForLocation('/second.html')
                ->assertSee('The second page');
        });
    }

    /**
     * Scoping with @dusk selectors and within(), body unchanged.
     */
    public function test_scoped_interaction(): void
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/index.html')
                ->assertSeeIn('@headline', 'Welcome to Dawn')
                ->within('@panel', function (Browser $panel) {
                    $panel->assertSee('Panel Title')
                        ->assertDontSee('Welcome to Dawn');
                })
                ->assertVisible('@panel')
                ->assertMissing('#hidden-message');
        });
    }

    /**
     * Ported from laravel/dusk's own real-browser suite
     * (tests/Browser/BrowserTest::test_it_handle_wait_for_text_in, 8.x) -
     * body unchanged except the fixture URL.
     */
    public function test_it_handle_wait_for_text_in(): void
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/wait.html')
                ->assertSeeIn('@copy-button', 'Copy')
                ->press('@copy-button')
                ->assertSeeIn('@copy-button', 'Copied!')
                ->waitForTextIn('@copy-button', 'Copy', 3);
        });
    }

    /**
     * Multiple browsers, as in Dusk's multi-browser documentation example.
     */
    public function test_multiple_browsers(): void
    {
        $this->browse(function (Browser $first, Browser $second) {
            $first->visit('/index.html')
                ->assertSee('Welcome to Dawn');

            $second->visit('/second.html')
                ->assertSee('The second page');

            $first->assertTitle('Dawn Fixture');
            $second->assertTitle('Second Page');
        });
    }
}
